name: Build and Release

on:
  push:
    branches: [ "main" ]  # Agregamos trigger en push a main
    tags: [ 'v*' ]
  workflow_dispatch:      # Permite ejecutar el workflow manualmente

permissions:
  contents: write        # Agregamos permisos explícitos

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Instalar dependencias
        run: |
          npm install
          npm install -g electron-builder
          
      - name: Instalar dependencias de Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools
          
      - name: Compilar para Windows
        if: matrix.os == 'windows-latest'
        run: npm run build:win
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Compilar para macOS
        if: matrix.os == 'macos-latest'
        run: npm run build:mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Compilar para Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
